version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831'
      - "16686:16686"
    volumes:
      - jaeger_data:/var/lib/jaeger
    # environment:
    #   - JAEGER_USERNAME=admin
    #   - JAEGER_PASSWORD=admin
    #   - JAEGER_SERVICE_NAME=jaeger

  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/var/lib/loki
    # send Loki traces to Jaeger
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/var/lib/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    # environment:
    #   - PROMETHEUS_USERNAME=admin
    #   - PROMETHEUS_PASSWORD=admin

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/hotrod_metrics_logs.json:/etc/grafana/provisioning/dashboards/hotrod_metrics_logs.json
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=admin
    #   - GF_SECURITY_ADMIN_USER=admin

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - '8080:8080'
      - '8083:8083'
    command: ["-m","prometheus","all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

volumes:
  elastic:
    driver: local
  kibana:
    driver: local
  loki_data:
    driver: local
  prometheus_data: 
    driver: local
  grafana_data:
    driver: local
  jaeger_data:
    driver: local
