version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
      ES_USERNAME: elastic
      ES_PASSWORD: ${ELASTIC_PASSWORD}
      es.tls.skip-host-verify: true
      # es.version: 7
      # es.index-prefix: jaeger-
      # es.create-index-templates: false
    # depends_on:
    #   - elasticsearch

  prometheus:
    image: prom/prometheus
    # platform: linux/amd64
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana


volumes:
  elastic:
    driver: local
  kibana:
    driver: local
  prometheus: 
    driver: ./
  grafana:
    driver: local

networks:
  default:
    driver: bridge