version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:7.17.5
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - transport.host= 0.0.0.0
      # - http.cors.enabled=true    # 是否支持跨域，是：true // 这里设置不起作用，但是可以将此文件映射到宿主机进行修改，然后重启，解决跨域
      # - http.cors.allow-origin="*" # 表示支持所有域名      // 这里设置不起作用，但是可以将此文件映射到宿主机进行修改，然后重启，解决跨域
      # - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  kibana:
    image: kibana:7.17.5
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - kibana:/usr/share/kibana/config

  head:
    image: mobz/elasticsearch-head:5
    restart: always
    ports:
      - 9100:9100

volumes:
  elastic:
    driver: local
  kibana:
    driver: local
  prometheus: 
    driver: ./
  grafana:
    driver: local

networks:
  default:
    driver: bridge